#
#        PremiumPvP
#     By AlmostSomeone
#

# Please do not change this version
version: 0.1

# Keep this setting enabled for the best experience with PremiumPvP
# If your server runs on a not supported fork, it might be worth it to test the new update on a test server first.
update-notify: true

# Languages supported: EN, NL
# Please keep in mind that this language setting only affects the messages in the "messages" folder.
# Things like scoreboards, signs and other things are customizable through their own configurations.
language: EN

# Configure this part when you wish to save data like stats, kits, guilds, cosmetics in MySQL
# If not enabled, the data will be stored in local JSON files in the "data" folder.
# There is a migrate command if you wish to migrate your local data to MySQL later on.

# We support different methods of storing data. DO NOT TOUCH THIS UNLESS YOU KNOW WHAT YOU ARE DOING.
# - SQLite: This is the default local Database.sql file and is recommended if you don't need to retrieve data from other places.
# - MySQL: This is the recommended way of storing data if you need to retrieve data from other places like multiple servers or websites.
storage:
  method: mysql
  host: localhost
  port: 3306
  username: root
  password: root
  database: premiumpvp
  table: data
  prefix: ppvp

# Configure how players can participate in KitPvP
# I'd recommend leaving this as it is if you only have this gamemode on the server.
# This is useful if you have multiple gamemodes in one server, since PremiumPvP will not interact with players that are not "joined".
participate:
  join:
    server: true # Join the KitPvP on server join
    command: false # Allow users to join with /kitpvp join
  leave:
    command: false # Allows users to leave with /kitpvp leave
    execute-command: "lobby {player}" # Allows you to execute console commands when someone uses /kitpvp leave.

# Here are the basic game settings.
# This allows you to modify the pvp experience to your likings.
#settings:
#  kit-customization:
#    enabled: true
#    permission:
#      enabled: true
#      name: premiumpvp.kit.customize
#  healthbar:
#    enabled: true
#    message: "&f%player_health% &c%symbol_heart%"
#  tablist:
#    enabled: true
#    header: "\n &5&lExampleServer \n &71.8.9 is recommended \n"
#    footer: "\n &7Players: &5%server_online% &7- TPS: &5%server_tps% &7- Ping &5%player_ping% ms \n\n &7play.exampleserver.com \n"
#  combattimer:
#    enabled: true
#    seconds: 10
#    kill-on-leave: true
#  banknotes:
#    enabled: false
#    lose-on-death: true
#    lose-on-spawn: false
#    lose-on-leave: false
#  soups:
#    enabled: true
#    instant: true
#    keep-bowl: false
#    health: 5
#  drop-items: false

# Configure the basics of the guild system.
# The permissions within a guild can be configured by the guild leader or by those with the correct guild permissions.
#guilds:
#  tags:
#    enabled: true
#    max-length: 4
#    default-color: 7

# The server's economy settings.
# Please configure this carefully, especially when your server is already launched.
#economy:
#  starters-balance: 100
#  kill-reward: 10

# The duels' system allows your players to go in private fights against each other.
# Configure the system here to make it work how you want it.
#duels:
#  settings:
#    be-in-spawn: true
#    broadcast-win: true
#    count-stats: false
#    allow-bids: true
#    allow-custom-kits: true
#    allow-abilities: false
#    allow-spectating: true

# Configure the commands to your likings.
# You can toggle commands, change their names, add aliases, set their descriptions and also set permissions.
# Please do not remove a command, this will cause problems.
commands:
  main: # The main command can not be disabled, can not have permissions and the name can not be changed.
    description: "Manage your KitPvP experience"
    aliases:
      - kp
      - premiumpvp
      - pvp
  world:
    enabled: true # This will completely enable or disable the command.
    name: world # The name of the command. For example if the name is "world" the command would be /world
    description: "Teleport between worlds" # The description is used for Bukkit's /help system.
    aliases:
      - worlds
    permission: # The permission you need to execute this command
      enabled: true # If you need the permission, set to "false" to make it so everyone can do this. (Not recommended for this command)
      name: premiumpvp.command.world # The permission they would need to execute this command.
#  coins:
#    enabled: true
#    name: coins
#    description: "See how many coins you have"
#    aliases:
#      - coin
#      - balance
#      - bal
#    permission:
#      enabled: false
#      name: premiumpvp.command.coins
#  guild:
#    enabled: true
#    name: guild
#    description: "Manage your guilds"
#    aliases:
#      - guilds
#      - g
#    permissions:
#      enabled: false
#      name: premiumpvp.command.guild
#  duels:
#    enabled: true
#    description: "Invite your friend for a fair fight"
#    aliases:
#      - duels
#      - 1v1
#    permission:
#      enabled: false
#      name: premiumpvp.command.duels

# Performance
# The following settings are used to configure the performance of the plugin.
# Please configure this carefully, especially when your server is already launched.
performance:
  caching:
    read-on-join: false # If you set this to true, the plugin will (re)cache the player's data when they join. Useful for Bungeecord configurations
    write-on-leave: false # If you set this to true, the plugin will write the player's data to the database when they leave. Useful for Bungeecord configurations
  auto-save:
    enabled: true # If you set this to true, the plugin will automatically save the data
    interval: 300 # The interval in seconds.

# World settings allow you to configure settings for your worlds.
# For example, you can lock a world to specific weather types, making it easy to add themes to your maps.
# You can also set a gamemode, which a player will switch to when visiting this world.
world-settings:
  global: # These settings are the default for all maps loaded by PremiumPvP
    void: true # If you enable this, there will be no world generation.
    type: FLAT # You can set this to NORMAL, FLAT, LARGE_BIOMES, AMPLIFIED
    generate-structures: false # Enabling this allows the generation of structures like villages and temples
    gamemode: ADVENTURE # Players visiting this world will be forced to this gamemode, disable this by setting it to NONE
    weather-lock: CLEAR # You can lock the weather to CLEAR. Disable this by setting it to NONE
    hunger: false # If you enable this, players will be able to get hungry in this world
  duels: # These settings count for all Duels maps, overriding "global"
    void: true
    type: FLAT
    generate-structures: false
    gamemode: ADVENTURE
    weather-lock: CLEAR
    hunger: false
  specifics:  # These are settings for specific worlds. Exceptions on duels worlds can also be added here. Adding a non-existent world will make PremiumPvP generate this world.
    world:
      # If your server's default world is "world", we can not change: void, type or generate-structures.
      # You can however use PremiumPvP as a void generator in your bukkit.yml.
      # To do this, read this page https://bukkit.fandom.com/wiki/Bukkit.yml#.2AOPTIONAL.2A_worlds
      gamemode: ADVENTURE
      weather-lock: CLEAR
      hunger: false
    ffa: # This will generate a new world called "FFA", and will load this world every time the plugin (re)starts.
      void: true
      type: FLAT
      generate-structures: false
      gamemode: ADVENTURE
      weather-lock: CLEAR
      hunger: false