name: ${project.name}
main: ${project.groupId}.premiumpvp.Main
version: ${project.version}
api-version: 1.18
load: STARTUP
website: ${project.url}
description: ${project.description}
author: AlmostSomeone
softdepend: [PlaceholderAPI]

commands:
  kitpvp:
    description: test