name: ${project.name}
main: ${project.groupId}.${project.artifactId}.PremiumPvP
version: ${project.version}
api-version: 1.19
load: STARTUP
website: ${project.url}
description: ${project.description}
author: AlmostSomeone
softdepend: [PlaceholderAPI, ProtocolLib]